"""
Defines
"""
FOLDER_MODULE_MODULE_NAME = "Module"
FOLDER_MODULE_LOGIC_NAME = "Logic"
FOLDER_MODULE_LOGIC_INTERACTOR_NAME = "Interactor"
FOLDER_MODULE_UI = "UI"
FOLDER_MODULE_UI_PRESENTER = "Presenter"
FOLDER_MODULE_UI_VIEW = "View"
FOLDER_MODULE_UI_WIREFRAME = "Wireframe"
"""
End Defines
"""